### ISSUE TITLE
Quartz解析报错

### ISSUE THREAD

**Issue by lgtianxiawudi** [abichinger/vue-js-cron#62]
![image](https://github.com/user-attachments/assets/130d9d5d-e936-4be7-b1e8-07287d75a135)

Caused by: java.lang.RuntimeException: CronExpression '0 * * ? 1 0' is invalid.
	at org.quartz.CronScheduleBuilder.cronSchedule(CronScheduleBuilder.java:111)
	... 87 common frames omitted
Caused by: java.text.ParseException: Day-of-Week values must be between 1 and 7
	at org.quartz.CronExpression.addToSet(CronExpression.java:996)
	at org.quartz.CronExpression.storeExpressionVals(CronExpression.java:685)
	at org.quartz.CronExpression.buildExpression(CronExpression.java:487)
	at org.quartz.CronExpression.<init>(CronExpression.java:276)
	at org.quartz.CronScheduleBuilder.cronSchedule(CronScheduleBuilder.java:107)
	... 88 common frames omitted

**Comment by abichinger** [comment]
f8cbe3a4fe1a40935976bed91b219c2a610200fe
